### ISSUE TITLE
npm install fails on windows 10

### ISSUE THREAD

**Issue by basmith7** [vinnymac/PokeNurse#1]
```
> sleep@3.0.1 install C:\Users\User\Desktop\PokeNurse\node_modules\sleep
> node-gyp rebuild

C:\Users\User\Desktop\PokeNurse\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User\Desktop\PokeNurse\node_modules\sleep
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
pokenurse@1.0.0 C:\Users\User\Desktop\PokeNurse
+-- bootstrap@3.3.7
+-- electron-packager@7.3.0
| +-- asar@0.11.0
| | +-- chromium-pickle-js@0.1.0
| | +-- commander@2.9.0
| | | `-- graceful-readlink@1.0.1
| | +-- cuint@0.2.1
| | +-- glob@6.0.4
| | | +-- inflight@1.0.5
| | | | `-- wrappy@1.0.2
| | | +-- inherits@2.0.1
| | | `-- once@1.3.3
| | +-- minimatch@3.0.2
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | +-- mkdirp@0.5.1
| | | `-- minimist@0.0.8
| | `-- mksnapshot@0.3.0
| |   +-- decompress-zip@0.3.0
| |   | +-- binary@0.3.0
| |   | | +-- buffers@0.1.1
| |   | | `-- chainsaw@0.1.0
| |   | |   `-- traverse@0.3.9
| |   | +-- mkpath@0.1.0
| |   | +-- nopt@3.0.6
| |   | | `-- abbrev@1.0.9
| |   | +-- q@1.4.1
| |   | +-- readable-stream@1.1.14
| |   | | `-- isarray@0.0.1
| |   | `-- touch@0.0.3
| |   |   `-- nopt@1.0.10
| |   +-- fs-extra@0.26.7
| |   `-- request@2.55.0
| |     +-- aws-sign2@0.5.0
| |     +-- bl@0.9.5
| |     | `-- readable-stream@1.0.34
| |     |   `-- isarray@0.0.1
| |     +-- caseless@0.9.0
| |     +-- combined-stream@0.0.7
| |     | `-- delayed-stream@0.0.5
| |     +-- form-data@0.2.0
| |     | `-- async@0.9.2
| |     +-- har-validator@1.8.0
| |     | `-- bluebird@2.10.2
| |     +-- hawk@2.3.1
| |     +-- http-signature@0.10.1
| |     | +-- asn1@0.1.11
| |     | +-- assert-plus@0.1.5
| |     | `-- ctype@0.5.3
| |     +-- mime-types@2.0.14
| |     | `-- mime-db@1.12.0
| |     +-- oauth-sign@0.6.0
| |     `-- qs@2.4.2
| +-- electron-download@2.1.2
| | +-- debug@2.2.0
| | | `-- ms@0.7.1
| | +-- home-path@1.0.3
| | +-- mv@2.1.1
| | | +-- ncp@2.0.0
| | | `-- rimraf@2.4.5
| | |   `-- glob@6.0.4
| | +-- nugget@1.6.2
| | | +-- pretty-bytes@1.0.4
| | | | +-- get-stdin@4.0.1
| | | | `-- meow@3.7.0
| | | |   +-- camelcase-keys@2.1.0
| | | |   +-- loud-rejection@1.6.0
| | | |   | +-- currently-unhandled@0.4.1
| | | |   | | `-- array-find-index@1.0.1
| | | |   | `-- signal-exit@3.0.0
| | | |   +-- map-obj@1.0.1
| | | |   +-- normalize-package-data@2.3.5
| | | |   | +-- hosted-git-info@2.1.5
| | | |   | +-- is-builtin-module@1.0.0
| | | |   | | `-- builtin-modules@1.1.1
| | | |   | +-- semver@5.3.0
| | | |   | `-- validate-npm-package-license@3.0.1
| | | |   |   +-- spdx-correct@1.0.2
| | | |   |   | `-- spdx-license-ids@1.2.2
| | | |   |   `-- spdx-expression-parse@1.0.2
| | | |   |     `-- spdx-exceptions@1.0.5
| | | |   +-- object-assign@4.1.0
| | | |   +-- read-pkg-up@1.0.1
| | | |   | +-- find-up@1.1.2
| | | |   | | `-- path-exists@2.1.0
| | | |   | `-- read-pkg@1.1.0
| | | |   |   +-- load-json-file@1.1.0
| | | |   |   | +-- parse-json@2.2.0
| | | |   |   | | `-- error-ex@1.3.0
| | | |   |   | |   `-- is-arrayish@0.2.1
| | | |   |   | +-- pify@2.3.0
| | | |   |   | `-- strip-bom@2.0.0
| | | |   |   |   `-- is-utf8@0.2.1
| | | |   |   `-- path-type@1.1.0
| | | |   +-- redent@1.0.0
| | | |   | +-- indent-string@2.1.0
| | | |   | | `-- repeating@2.0.1
| | | |   | |   `-- is-finite@1.0.1
| | | |   | `-- strip-indent@1.0.1
| | | |   `-- trim-newlines@1.0.0
| | | +-- progress-stream@1.2.0
| | | | +-- speedometer@0.1.4
| | | | `-- through2@0.2.3
| | | |   +-- readable-stream@1.1.14
| | | |   | `-- isarray@0.0.1
| | | |   `-- xtend@2.1.2
| | | |     `-- object-keys@0.4.0
| | | +-- single-line-log@0.4.1
| | | `-- throttleit@0.0.2
| | +-- path-exists@1.0.0
| | `-- rc@1.1.6
| |   +-- deep-extend@0.4.1
| |   +-- ini@1.3.4
| |   `-- strip-json-comments@1.0.4
| +-- electron-osx-sign@0.3.1
| +-- extract-zip@1.5.0
| | +-- concat-stream@1.5.0
| | | +-- readable-stream@2.0.6
| | | | +-- core-util-is@1.0.2
| | | | +-- isarray@1.0.0
| | | | +-- process-nextick-args@1.0.7
| | | | `-- string_decoder@0.10.31
| | | `-- typedarray@0.0.6
| | +-- debug@0.7.4
| | +-- mkdirp@0.5.0
| | | `-- minimist@0.0.8
| | `-- yauzl@2.4.1
| |   `-- fd-slicer@1.0.1
| |     `-- pend@1.2.0
| +-- fs-extra@0.28.0
| | +-- graceful-fs@4.1.5
| | +-- jsonfile@2.3.1
| | +-- klaw@1.3.0
| | +-- path-is-absolute@1.0.0
| | `-- rimraf@2.5.4
| |   `-- glob@7.0.5
| |     `-- fs.realpath@1.0.0
| +-- get-package-info@0.0.2
| | `-- lodash.get@4.4.1
| +-- minimist@1.2.0
| +-- plist@1.2.0
| | +-- base64-js@0.0.8
| | +-- util-deprecate@1.0.2
| | +-- xmlbuilder@4.0.0
| | | `-- lodash@3.10.1
| | `-- xmldom@0.1.22
| +-- rcedit@0.5.1
| +-- resolve@1.1.7
| `-- run-series@1.1.4
+-- electron-prebuilt@1.3.1
+-- jquery@3.1.0
+-- node-pogo-protos@1.1.1
| `-- protobufjs@5.0.1
|   +-- ascli@1.0.0
|   | +-- colour@0.7.1
|   | `-- optjs@3.2.2
|   +-- bytebuffer@5.0.1
|   +-- glob@5.0.15
|   `-- yargs@3.32.0
|     +-- camelcase@2.1.1
|     +-- cliui@3.2.0
|     | +-- strip-ansi@3.0.1
|     | | `-- ansi-regex@2.0.0
|     | `-- wrap-ansi@2.0.0
|     +-- decamelize@1.2.0
|     +-- os-locale@1.4.0
|     | `-- lcid@1.0.0
|     |   `-- invert-kv@1.0.0
|     +-- string-width@1.0.1
|     | +-- code-point-at@1.0.0
|     | | `-- number-is-nan@1.0.0
|     | `-- is-fullwidth-code-point@1.0.0
|     +-- window-size@0.1.4
|     `-- y18n@3.2.1
`-- pogobuf@1.4.0
  +-- bluebird@3.4.1
  +-- bluebird-retry@0.8.0
  +-- gpsoauthnode@0.0.5
  | `-- crypto-js@3.1.6
  +-- long@3.2.0
  `-- request@2.74.0
    +-- aws-sign2@0.6.0
    +-- aws4@1.4.1
    +-- bl@1.1.2
    +-- caseless@0.11.0
    +-- combined-stream@1.0.5
    | `-- delayed-stream@1.0.0
    +-- extend@3.0.0
    +-- forever-agent@0.6.1
    +-- form-data@1.0.0-rc4
    | `-- async@1.5.2
    +-- har-validator@2.0.6
    | +-- chalk@1.1.3
    | | +-- ansi-styles@2.2.1
    | | +-- escape-string-regexp@1.0.5
    | | +-- has-ansi@2.0.0
    | | `-- supports-color@2.0.0
    | +-- is-my-json-valid@2.13.1
    | | +-- generate-function@2.0.0
    | | +-- generate-object-property@1.2.0
    | | | `-- is-property@1.0.2
    | | +-- jsonpointer@2.0.0
    | | `-- xtend@4.0.1
    | `-- pinkie-promise@2.0.1
    |   `-- pinkie@2.0.4
    +-- hawk@3.1.3
    | +-- boom@2.10.1
    | +-- cryptiles@2.0.5
    | +-- hoek@2.16.3
    | `-- sntp@1.0.9
    +-- http-signature@1.1.1
    | +-- assert-plus@0.2.0
    | +-- jsprim@1.3.0
    | | +-- extsprintf@1.0.2
    | | +-- json-schema@0.2.2
    | | `-- verror@1.3.6
    | `-- sshpk@1.9.2
    |   +-- asn1@0.2.3
    |   +-- assert-plus@1.0.0
    |   +-- dashdash@1.14.0
    |   | `-- assert-plus@1.0.0
    |   +-- ecc-jsbn@0.1.1
    |   +-- getpass@0.1.6
    |   | `-- assert-plus@1.0.0
    |   +-- jodid25519@1.0.2
    |   +-- jsbn@0.1.0
    |   `-- tweetnacl@0.13.3
    +-- is-typedarray@1.0.0
    +-- isstream@0.1.2
    +-- json-stringify-safe@5.0.1
    +-- mime-types@2.1.11
    | `-- mime-db@1.23.0
    +-- node-uuid@1.4.7
    +-- oauth-sign@0.8.2
    +-- qs@6.2.1
    +-- stringstream@0.0.5
    +-- tough-cookie@2.3.1
    `-- tunnel-agent@0.4.3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@3.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\Desktop\PokeNurse\npm-debug.log
```

There is no npm-debug.log

**Comment by 3of5-IQ** [comment]
I get the same error on Ubuntu also.

**Comment by basmith7** [comment]
the app still works even with this error

**Comment by 3of5-IQ** [comment]
Unfortunately, mine does not. I followed the installation instructions and still nothing. How were you able to access the front end page?

**Comment by duhminick** [comment]
I've removed sleep from the project and use Javascript's built-in timing events now.  If you pull the repo now, it should be fixed.

**Comment by 3of5-IQ** [comment]
Hi, Still getting the same error message. Could you take a look and let me know what you think. I would really love to contribute to this also.

![error](https://cloud.githubusercontent.com/assets/13574377/17278102/4e498ec8-5709-11e6-898b-e075d4c6f1de.JPG)
