### ISSUE TITLE
Selected counter does not refresh after transfer

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#125]
I just selected 12 pokemon, transfered them (using transfer all) and the selected counter was still showing 12. When I selected another pokemon it updated to 13.

I just followed the same steps and reproduced the bug, same result. Clicking the refresh button didnt refresh the counter either.

**Comment by mackhankins** [comment]
I'll try to reproduce your error.  What OS?

**Comment by iPaulis** [comment]
Windows 10

**Comment by mackhankins** [comment]
@vinnymac `index.js?7168:264 Uncaught TypeError: Cannot read property 'pokemon_id' of null`

**Comment by mackhankins** [comment]
@iPaulis we had this working and I think we pushed up some old code.  We'll push out 1.3.1 soon.  Good catch.

**Comment by vinnymac** [comment]
Just pushed a fix for this to develop. We can fix the evolves issue and then release.

**Comment by mouson** [comment]
@vinnymac 

I'm MAC User and used v1.3.2, but this bug is still exist. when i evolve my pokemen.

**Comment by mackhankins** [comment]
@mouson I'm a mac user on 1.3.2 and I can't reproduce this error anymore.  How did you do it?

Edit: never mind I see it.

**Comment by mouson** [comment]
@mackhankins 

This gif record evolve my pokemen step. http://d.pr/i/1iGBP

that is old javascript file cache ?

**Comment by vinnymac** [comment]
Weird I guess the wrong binaries were selected, I will recompile and upload.

EDIT: I reuploaded them, you can try to redownload and see if that helps.
